forge 'https://forgeapi.puppetlabs.com/'

mod 'puppetlabs/yumrepo_core'
mod 'puppetlabs/apache'
mod 'puppetlabs/apt'
mod 'puppet/archive'
mod 'puppetlabs/concat'
mod 'puppetlabs/inifile'
mod 'puppetlabs/mysql'
mod 'puppet/redis'
mod 'puppet/php'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/stdlib'
mod 'puppet/systemd'
mod 'puppetlabs/vcsrepo'
mod 'puppet/icinga'
mod 'puppet/icinga2'
mod 'puppet/icingadb'
mod 'puppet/icingaweb2'

mod 'puppetlabs/chocolatey'
mod 'dylanratcliffe-windows_disk_facts'

mod 'profile', :local => true
