forge 'https://forgeapi.puppetlabs.com/'

mod 'puppetlabs/yumrepo_core'
mod 'puppetlabs/apache'
mod 'puppetlabs/apt'
mod 'puppet/archive'
mod 'puppetlabs/concat'
mod 'puppetlabs/inifile'
mod 'puppetlabs/mysql'
mod 'puppet/redis'
mod 'puppet/php'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/stdlib'
mod 'puppet/systemd'
mod 'puppetlabs/vcsrepo'
mod 'puppet/icinga'

mod 'theforeman/puppet'
mod 'puppet/extlib'

mod 'profile', :local => true

mod 'icinga2',
  :git => 'https://github.com/voxpupuli/puppet-icinga2',
  :branch => 'main'
mod 'icingadb',
  :git => 'https://github.com/voxpupuli/puppet-icingadb',
  :branch => 'main'
mod 'icingaweb2',
  :git => 'https://github.com/voxpupuli/puppet-icingaweb2',
  :branch => 'main'
